name: benchmark

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  JDK: '17'
  DISTRIBUTION: 'zulu'
  GRADLE_COMMAND: './gradlew --no-daemon'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          java-version: ${{ env.JDK }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: JMH
        run: ${{ env.GRADLE_COMMAND }} clean :zuul-core:jmh
